model:
  package: dgraph
  filename: ./src/service/dgraph/models_gen.go
client:
  package: dgraph
  filename: ./src/service/dgraph/client_gen.go
models:
  ID:
    model: github.com/99designs/gqlgen/graphql.ID
  Int:
    model: github.com/99designs/gqlgen/graphql.Int
  Float:
    model: github.com/99designs/gqlgen/graphql.Float
  String:
    model: github.com/99designs/gqlgen/graphql.String
  Boolean:
    model: github.com/99designs/gqlgen/graphql.Boolean
  DateTime:
    model: github.com/99designs/gqlgen/graphql.Time
endpoint:
  url: http://localhost:8080/graphql
query:
  - "./graphql/*.graphql" # Where are all the query files located?