addr: ":8081"
cert_file:
key_file:
logger:
  level: debug
trusted_proxy: false
service_endpoints:
- http://ot.example.com/v1
dgraph:
  graphql_endpoint: http://localhost:8088/graphql
open_trust:
  otid: "otid:ot.example.com"
  keys_refresh_hint: 3600
  user_types:
  - user
  - dev
  service_types:
  - agent
  - app
  - svc
  private_keys:
  - '{"kty":"EC","alg":"ES512","crv":"P-521","d":"AdXSdw87nB_NPVqNUHXe47BzofXghwlLxbpCbhw1ADh9F7AmxBEsgUnW_ynNEMvQPcJPcyEw1OkCK-_olsFkPdFQ","kid":"ySQYnCsV4cOZBxbHCv4E410k0gjTbi8WfJJwVkV6QqI","x":"AdtXGowadABABWC0FVolCYnRhiBEYdO6-bpyldNh1RrLVIDJJRJelA_O2UB9DyssCN8gLfJio3OdV8YH6uyfvOwb","y":"AX1Waed_878v_Y1JE2U3dLvAOIScuu_UVGUFZpQyB-hRTXMIQHTqEQw9os_Jcb491-0ZUANJZs_gne7srQ2yOCN6"}'
