name: OT-Auth Service Testing
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # use mysql in VM https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    # https://github.com/actions/virtual-environments/issues/576
    - name: run dgraph service
      run: |
        export TZ=UTC
        docker run --name dgraph -p 8088:8080 -d dgraph/standalone
        sleep 10s
        curl -X POST localhost:8088/admin/schema --data-binary '@graphql/schema/schema.graphql'

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: |
        CONFIG_FILE_PATH=${PWD}/config/testing.yaml APP_ENV=testing go test -p 1 -v ./...
